class BaseField(object):
    """ field count: 59 """
    fields = [
        "id",
        "area_of_job",
        "filename",
        "start_time",
        "end_time",
        "duration",
        "callnumber",
        "rep_no",
        "rep_group",
        "agent_no",
        "account_no",
        "rep_team",
        "calltype",
        "number_of_record",
        "region",
        "project_list",
        "satisfaction",
        "qa_no",
        "summarize_group",
        "summarize_class",
        "summarize_project",
        "summarize_content",
        "is_qa",
        "to_warehouse",
        "to_improvement",
        "isnormality",
        "type_of_service",
        "data_status",
        "data_status_2",
        "data_status_3",
        "group_leader",
        "cust_id",
        "cust_name",
        "audit_no",
        "phone_type",
        "verify_type",
        "staff_name",
        "bu_type",
        "rule_prompt",
        "years",
        "months",
        "days",
        "path",
        "filesize",
        "fileunique",
        "handledfilename",
        "plaintexta",
        "plaintextb",
        "speedresulta",
        "speedresultb",
        "tonea",
        "toneb",
        "blankinfo",
        "maxblanklen",
        "maxstartblankpos",
        "robspeeda",
        "robspeedb",
        "emotiona",
        "emotionb",
        "emotionvaluea",
        "emotionvalueb",
        "mapfilepath",
        "mapfilekey",
        "errors",
    ]

    integer_feilds = []
    float_feilds = ["duration", "maxblanklen", "maxstartblankpos"]

    extended_fields = []

    def __init__(self):
        if len(self.extended_fields) > 0:
            self.fields = self.fields + self.extended_fields
