CREATE DATABASE IF NOT EXISTS hengdaproject;

CREATE TABLE `hengda_project_voice_smartv_hive_main`(
  `row` string, 
  `update_time` string, 
  `file_name` string, 
  `start_time` string, 
  `duration` string, 
  `area_of_job` string, 
  `call_type` string, 
  `call_number` string, 
  `record_no` string, 
  `agent_no` string, 
  `rep_no` string, 
  `rep_team` string, 
  `rep_group` string, 
  `account_no` string, 
  `years` string, 
  `months` string, 
  `days` string, 
  `path` string, 
  `file_size` string, 
  `file_unique` string, 
  `handled_file_name` string, 
  `plain_text_a` string, 
  `plain_text_b` string, 
  `speed_result_a` string, 
  `speed_result_b` string, 
  `max_blank_len` string, 
  `max_start_blank_pos` string, 
  `blank_info` string, 
  `rob_speed_a` string, 
  `rob_speed_b` string, 
  `map_file_path` string, 
  `map_file_key` string, 
  `region` string, 
  `project_list` string, 
  `satisfaction` string, 
  `qa_no` string, 
  `summarize_group` string, 
  `summarize_class` string, 
  `summarize_project` string, 
  `summarize_content` string, 
  `is_qa` string, 
  `to_warehouse` string, 
  `to_improvement` string, 
  `is_normality` string, 
  `type_of_service` string, 
  `data_status` string, 
  `data_status_2` string, 
  `data_status_3` string, 
  `group_leader` string, 
  `cust_id` string, 
  `cust_name` string, 
  `audit_no` string, 
  `phone_type` string, 
  `verify_type` string, 
  `staff_name` string, 
  `bu_type` string, 
  `rule_prompt` string, 
  `similarity` string, 
  `emotiona` string, 
  `emotionb` string, 
  `emovaluea` string, 
  `emovalueb` string, 
  `gena` string, 
  `genb` string, 
  `tonea` string, 
  `toneb` string)
PARTITIONED BY ( 
  `recorddate` string)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY '|' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';