#!/bin/sh

INPUT=$1
OUTPUT=$2
LOG_FILEDIR=$3
LOG_FILENAME="wav2png.log"
CURRENT_DIR=`dirname $0`
RUNNER=`which java`

if [ "" = "${LOG_FILEDIR}" ]; then
    LOG_FILEDIR="${CURRENT_DIR}/../../logs"
fi

mkdir -p ${LOG_FILEDIR}
log_filepath="${LOG_FILEDIR}/${LOG_FILENAME}"

if [ -d ${INPUT} ]; then
	mkdir -p ${OUTPUT}
	for input_filepath in `find ${INPUT} -name "*.wav"`
	do
		filename=`basename ${input_filepath}`
		output_filepath=${OUTPUT}/${filename}".png"
		command="${RUNNER} -jar ${CURRENT_DIR}/CreateWaveform.jar ${input_filepath} ${output_filepath}"
		echo ${command} >> ${log_filepath}
		${command}
	done
fi
